In [1]:
from ultralytics import YOLO
import os
from pathlib import Path
from tqdm import tqdm
import numpy as np
import pandas as pd

### Load the pose estimator

In [2]:
pose = YOLO('yolo11m-pose.pt')

### Prepare DataFrame for data analysis

In [3]:
current_path = Path.cwd()
dataset_path = Path(os.path.join(current_path, 'datasets/fall_not_fall'))
dataset_path.exists()

True

In [23]:
def get_points(image_path, model, conf=0.8):
    results = model.predict(image_path, conf=conf, imgsz=640, verbose=False)
    keypoints = results[0].keypoints.xy.cpu().numpy()
    if len(keypoints) > 0:
        bboxes = results[0].boxes.xyxy[0].cpu().numpy().astype(int)
    else:
        bboxes = []

    return keypoints, bboxes

In [68]:
def nose_ref_point(point, nose):
    new_point = (float(point[0] - nose[0]), float(point[1] - nose[1]))
    return tuple(new_point)

In [89]:
def get_datapoints(dataset_path):
    dir_lst = ['train', 'test', 'valid']
    features, targets = [], []
    values = ['not fall', 'fall']

    for lst in dir_lst:
        path = Path(os.path.join(dataset_path, lst))
        print(f'Prepared for {path}')
        if path.exists:
            # Check for valid image extension
            img_ext = ['*.jpg', '*.jpeg', '*.png']
            images_path = []
            for ext in img_ext:
                images_path.extend(Path(os.path.join(path, 'images')).glob(ext))

            # Search for image annotation path
            for image_path in tqdm(images_path, desc='Processing image...'):
                annot_path = Path(os.path.join(path, 'labels', f'{image_path.stem}.txt'))
                
                if annot_path.exists():
                    keypoints, bboxes = get_points(image_path=image_path, model=pose)
                    
                    lines = []
                    with open(annot_path, 'r') as file:
                        lines = file.readlines()

                    if keypoints.shape[0] != len(lines):
                        print(f'Problem occured with file "{annot_path}"')
                        print(keypoints.shape, len(lines))
                        continue
                    
                    for points, line in zip(keypoints, lines):
                        nose = points[0]
                        new_point = list(map(lambda p: nose_ref_point(p, nose), points))
                        new_point.append(bboxes[:2])
                        new_point.append(bboxes[2:])
                        features.append(new_point)
                        targets.append(values[int(line.strip().split(' ')[0])])

    # Convert list to numpy array
    # features = np.array(features)
    # targets = np.array(targets)

    return features, targets

In [90]:
features, targets = get_datapoints(dataset_path=dataset_path)
# features.shape, targets.shape

Prepared for /home/labuser/Joy/IntellgiCare/datasets/fall_not_fall/train

Processing image...:  46%|████▌     | 85/185 [00:02<00:03, 32.91it/s]

Problem occured with file "/home/labuser/Joy/IntellgiCare/datasets/fall_not_fall/train/labels/IMG_20220908_215739_jpg.rf.8f75b953299f805bd899a3f1ca57ae5e.txt"
(0, 17, 2) 1

Processing image...:  82%|████████▏ | 152/185 [00:04<00:00, 37.16it/s]

Problem occured with file "/home/labuser/Joy/IntellgiCare/datasets/fall_not_fall/train/labels/person-63-_jpg.rf.052fbf07d4f712aed5cd94405e2a53c5.txt"
(1, 17, 2) 2

Processing image...: 100%|██████████| 185/185 [00:05<00:00, 35.44it/s]

Prepared for /home/labuser/Joy/IntellgiCare/datasets/fall_not_fall/test

Processing image...: 100%|██████████| 25/25 [00:00<00:00, 37.04it/s]

Prepared for /home/labuser/Joy/IntellgiCare/datasets/fall_not_fall/valid

Processing image...: 100%|██████████| 25/25 [00:00<00:00, 33.64it/s]

In [91]:
features

[[(0.0, 0.0),
  (2.969818115234375, -3.343017578125),
  (4.75787353515625, -4.371337890625),
  (16.017974853515625, 0.763031005859375),
  (24.252685546875, -3.33013916015625),
  (22.419921875, 26.064361572265625),
  (41.724853515625, 18.137359619140625),
  (19.771759033203125, 60.0574951171875),
  (51.76800537109375, 47.167877197265625),
  (5.402587890625, 86.25283813476562),
  (41.0611572265625, 67.84780883789062),
  (21.951141357421875, 83.23684692382812),
  (35.077728271484375, 76.83175659179688),
  (16.240264892578125, 122.56332397460938),
  (31.33636474609375, 111.39404296875),
  (20.480865478515625, 165.65145874023438),
  (37.42388916015625, 149.59182739257812),
  array([291, 289]),
  array([366, 492])],
 [(0.0, 0.0),
  (2.203216552734375, -5.118621826171875),
  (-5.887847900390625, -6.091644287109375),
  (-5.5640869140625, -3.91717529296875),
  (-26.0697021484375, -5.3277587890625),
  (-1.70098876953125, 21.91534423828125),
  (-49.882415771484375, 22.85565185546875),
  (5.635406494140625, 59.436004638671875),
  (-70.62771606445312, 64.62896728515625),
  (7.100677490234375, 90.60125732421875),
  (-67.525634765625, 100.11004638671875),
  (-15.848541259765625, 95.57498168945312),
  (-46.81585693359375, 96.55389404296875),
  (-20.456024169921875, 138.37966918945312),
  (-58.841339111328125, 140.6790771484375),
  (-32.686309814453125, 178.5489501953125),
  (-61.57403564453125, 189.4188232421875),
  array([249, 312]),
  array([347, 555])],
 [(0.0, 0.0),
  (-0.56451416015625, -7.63092041015625),
  (-8.668426513671875, -8.126861572265625),
  (-25.22955322265625, -3.575927734375),
  (-40.944427490234375, -3.416046142578125),
  (-30.344024658203125, 41.03179931640625),
  (-65.21206665039062, 44.718902587890625),
  (-17.309722900390625, 111.17706298828125),
  (-71.0257568359375, 115.06954956054688),
  (-11.33380126953125, 169.08639526367188),
  (-34.4765625, 172.41000366210938),
  (-30.401611328125, 170.22705078125),
  (-52.78472900390625, 174.1461181640625),
  (-52.381683349609375, 242.91421508789062),
  (-61.906036376953125, 248.68038940429688),
  (-58.222900390625, 299.1534423828125),
  (-67.9521484375, 316.8498229980469),
  array([232, 169]),
  array([347, 561])],
 [(0.0, 0.0),
  (12.612579345703125, -6.0320587158203125),
  (-10.45867919921875, -7.76226806640625),
  (25.917266845703125, 8.030670166015625),
  (-28.996856689453125, 3.712005615234375),
  (46.2015380859375, 54.033538818359375),
  (-58.212921142578125, 49.78639221191406),
  (71.405517578125, 107.01434326171875),
  (-93.59994506835938, 99.63003540039062),
  (72.35000610351562, 155.06396484375),
  (-95.0213623046875, 157.5733642578125),
  (21.578704833984375, 165.56607055664062),
  (-45.820343017578125, 164.13714599609375),
  (31.1717529296875, 230.83670043945312),
  (-65.32342529296875, 231.77801513671875),
  (30.572509765625, 285.08770751953125),
  (-58.79730224609375, 291.7757263183594),
  array([195, 154]),
  array([398, 518])],
 [(0.0, 0.0),
  (4.9658203125, -3.471710205078125),
  (5.11431884765625, -5.28509521484375),
  (26.09405517578125, 2.82830810546875),
  (23.7957763671875, -4.234710693359375),
  (39.92218017578125, 34.65142822265625),
  (38.3875732421875, 21.74945068359375),
  (37.54119873046875, 75.71722412109375),
  (29.748046875, 51.44708251953125),
  (22.300140380859375, 106.97628784179688),
  (12.896728515625, 76.3055419921875),
  (29.7509765625, 101.79486083984375),
  (29.24359130859375, 92.95401000976562),
  (27.943695068359375, 141.6373291015625),
  (26.30059814453125, 128.94952392578125),
  (27.743408203125, 180.53558349609375),
  (21.303436279296875, 164.8646240234375),
  array([294, 258]),
  array([382, 486])],
 [(0.0, 0.0),
  (-8.532196044921875, -8.60919189453125),
  (6.1270751953125, -7.45263671875),
  (-33.534820556640625, -3.127471923828125),
  (24.54132080078125, -2.886322021484375),
  (-60.61268615722656, 48.31874084472656),
  (57.2574462890625, 48.53681945800781),
  (-97.42771911621094, 107.72830200195312),
  (94.96389770507812, 109.58251953125),
  (-98.31143188476562, 150.85455322265625),
  (98.17568969726562, 159.14132690429688),
  (-42.43035888671875, 167.794189453125),
  (35.740447998046875, 166.461181640625),
  (-43.314208984375, 241.61978149414062),
  (30.3873291015625, 242.63214111328125),
  (-43.547088623046875, 315.9617004394531),
  (31.5479736328125, 311.0692443847656),
  array([185, 143]),
  array([415, 525])],
 [(0.0, 0.0),
  (11.33367919921875, -7.021087646484375),
  (-6.248626708984375, -7.34454345703125),
  (34.16357421875, -2.585205078125),
  (-10.938629150390625, -3.9345703125),
  (53.166412353515625, 38.201446533203125),
  (-22.0855712890625, 31.074676513671875),
  (66.23931884765625, 91.22872924804688),
  (-47.2413330078125, 74.19720458984375),
  (49.05511474609375, 141.79241943359375),
  (-58.09210205078125, 119.96063232421875),
  (22.7620849609375, 135.54440307617188),
  (-25.76708984375, 129.11602783203125),
  (21.751495361328125, 196.4466552734375),
  (-33.57814025878906, 184.49169921875),
  (20.892791748046875, 241.75579833984375),
  (-26.98291015625, 227.224853515625),
  array([211, 296]),
  array([384, 615])],
 [(0.0, 0.0),
  (10.12982177734375, -4.3037109375),
  (-4.140960693359375, -6.27166748046875),
  (29.800445556640625, 0.75335693359375),
  (-6.374114990234375, -4.0594482421875),
  (45.20751953125, 29.153472900390625),
  (-11.133758544921875, 22.012420654296875),
  (64.189453125, 66.32363891601562),
  (-24.975616455078125, 52.1549072265625),
  (48.810577392578125, 101.84368896484375),
  (-34.35174560546875, 85.48397827148438),
  (27.671051025390625, 107.72088623046875),
  (-9.26361083984375, 102.25439453125),
  (37.010284423828125, 155.92340087890625),
  (-17.268280029296875, 142.960205078125),
  (42.370452880859375, 179.27947998046875),
  (-9.16943359375, 168.38095092773438),
  array([252, 287]),
  array([372, 530])],
 [(0.0, 0.0),
  (12.415557861328125, -8.726165771484375),
  (8.89434814453125, -10.0889892578125),
  (55.711639404296875, -0.6318817138671875),
  (45.22418212890625, -8.688156127929688),
  (67.08132934570312, 58.76048278808594),
  (85.47402954101562, 53.648895263671875),
  (74.42919921875, 143.21726989746094),
  (83.32086181640625, 139.86537170410156),
  (35.32720947265625, 223.19847106933594),
  (41.06317138671875, 200.6124725341797),
  (61.036468505859375, 220.3606719970703),
  (72.99996948242188, 214.2959442138672),
  (64.7340087890625, 315.03948974609375),
  (87.05703735351562, 307.12603759765625),
  (90.3406982421875, 420.27410888671875),
  (81.99285888671875, 400.94677734375),
  array([220, 112]),
  array([385, 619])],
 [(0.0, 0.0),
  (5.188934326171875, 4.216094970703125),
  (10.70538330078125, -5.65081787109375),
  (25.671875, -8.15576171875),
  (30.6588134765625, -29.75653076171875),
  (33.31927490234375, -38.039764404296875),
  (27.896392822265625, -67.4434814453125),
  (-53.189208984375, -20.945587158203125),
  (-64.44464111328125, -64.35134887695312),
  (-61.12091064453125, 52.799713134765625),
  (-80.4390869140625, 8.3668212890625),
  (78.91897583007812, -82.15164184570312),
  (71.319580078125, -99.41888427734375),
  (14.547821044921875, -1.658233642578125),
  (-2.521942138671875, -42.9925537109375),
  (-22.338104248046875, 85.50143432617188),
  (-42.530670166015625, 49.300506591796875),
  array([227, 136]),
  array([474, 537])],
 [(0.0, 0.0),
  (-1.7440948486328125, -4.19500732421875),
  (3.8347625732421875, -4.79010009765625),
  (-5.3334197998046875, 1.25830078125),
  (29.524185180664062, -0.5740966796875),
  (-25.789962768554688, 31.315704345703125),
  (54.63130187988281, 31.74169921875),
  (-56.94593811035156, 64.995361328125),
  (85.18824768066406, 70.87081909179688),
  (-50.354156494140625, 95.72802734375),
  (68.19877624511719, 100.3739013671875),
  (-16.147903442382812, 110.31198120117188),
  (38.12269592285156, 109.96047973632812),
  (-30.200607299804688, 155.89276123046875),
  (39.82560729980469, 159.18798828125),
  (-39.79347229003906, 206.24078369140625),
  (39.13536071777344, 209.68157958984375),
  array([162, 301]),
  array([331, 558])],
 [(0.0, 0.0),
  (6.72027587890625, -4.24346923828125),
  (-1.226959228515625, -4.809417724609375),
  (27.82415771484375, -1.004974365234375),
  (4.8260498046875, -2.056365966796875),
  (42.36669921875, 28.662811279296875),
  (4.501190185546875, 23.636993408203125),
  (47.503662109375, 71.52212524414062),
  (-14.828643798828125, 48.437774658203125),
  (31.80029296875, 104.7728271484375),
  (-34.732696533203125, 49.325775146484375),
  (21.871337890625, 99.4508056640625),
  (-3.533935546875, 95.14202880859375),
  (25.65985107421875, 146.55447387695312),
  (-5.230133056640625, 136.27264404296875),
  (24.8465576171875, 192.41616821289062),
  (-4.812225341796875, 181.72103881835938),
  array([242, 313]),
  array([356, 557])],
 [(0.0, 0.0),
  (-5.92303466796875, -4.004150390625),
  (0.52923583984375, -4.4105224609375),
  (-25.366790771484375, -0.478515625),
  (8.471527099609375, -0.472259521484375),
  (-41.927154541015625, 24.90777587890625),
  (22.6396484375, 23.700775146484375),
  (-58.189208984375, 56.697845458984375),
  (47.420135498046875, 55.810546875),
  (-57.5162353515625, 80.231689453125),
  (41.0660400390625, 85.72821044921875),
  (-31.83978271484375, 90.38763427734375),
  (11.51434326171875, 90.61029052734375),
  (-37.896148681640625, 128.06201171875),
  (12.3167724609375, 127.80963134765625),
  (-43.20111083984375, 167.46548461914062),
  (13.058380126953125, 167.05789184570312),
  array([270, 298]),
  array([402, 507])],
 [(0.0, 0.0),
  (-5.970428466796875, -7.036468505859375),
  (-2.68817138671875, -5.60992431640625),
  (-38.711334228515625, -5.10382080078125),
  (-17.264678955078125, -1.499298095703125),
  (-64.95309448242188, 23.51458740234375),
  (-21.6568603515625, 35.912261962890625),
  (-75.14837646484375, 68.42874145507812),
  (-19.128204345703125, 88.35159301757812),
  (-62.067840576171875, 106.02325439453125),
  (-14.487884521484375, 125.08282470703125),
  (-70.96478271484375, 110.47238159179688),
  (-40.13201904296875, 117.49636840820312),
  (-71.83175659179688, 155.4312744140625),
  (-42.568267822265625, 163.21182250976562),
  (-77.37545776367188, 196.22225952148438),
  (-53.170013427734375, 211.39645385742188),
  array([296, 272]),
  array([401, 530])],
 [(0.0, 0.0),
  (5.8415679931640625, -7.3662109375),
  (-9.672012329101562, -6.702606201171875),
  (10.150039672851562, -3.2965087890625),
  (-28.32354736328125, -1.840484619140625),
  (25.557693481445312, 25.72784423828125),
  (-49.53004455566406, 28.448211669921875),
  (51.49781799316406, 48.965362548828125),
  (-90.57687377929688, 60.09320068359375),
  (62.29631042480469, 82.212158203125),
  (-75.55360412597656, 102.12936401367188),
  (18.978683471679688, 105.919921875),
  (-29.57720947265625, 108.80758666992188),
  (24.140823364257812, 149.92535400390625),
  (-36.10400390625, 158.32376098632812),
  (21.636734008789062, 185.24615478515625),
  (-42.26203918457031, 202.26824951171875),
  array([150, 296]),
  array([320, 559])],
 [(0.0, 0.0),
  (-8.04742431640625, -6.289093017578125),
  (-1.401824951171875, -5.594024658203125),
  (-39.18524169921875, -5.15960693359375),
  (-3.57867431640625, -3.3907623291015625),
  (-59.7711181640625, 25.269729614257812),
  (9.747772216796875, 26.927963256835938),
  (-73.29734802246094, 74.17581176757812),
  (30.458221435546875, 73.352294921875),
  (-64.482666015625, 108.29806518554688),
  (29.84515380859375, 111.25936889648438),
  (-47.475494384765625, 111.20828247070312),
  (1.880157470703125, 112.32717895507812),
  (-47.136138916015625, 163.374755859375),
  (1.662506103515625, 161.25747680664062),
  (-49.647186279296875, 217.6923828125),
  (0.288421630859375, 219.36407470703125),
  array([242, 179]),
  array([378, 453])],
 [(0.0, 0.0),
  (-8.807373046875, -9.4375),
  (1.15618896484375, -9.09844970703125),
  (-48.1722412109375, -16.14703369140625),
  (-7.45733642578125, -15.832061767578125),
  (-80.41091918945312, 20.5858154296875),
  (-4.2947998046875, 22.979400634765625),
  (-87.0908203125, 89.27346801757812),
  (18.00445556640625, 90.02346801757812),
  (-61.020721435546875, 124.52081298828125),
  (25.74639892578125, 153.74734497070312),
  (-67.94830322265625, 139.21392822265625),
  (-13.56292724609375, 142.26559448242188),
  (-64.52996826171875, 208.26885986328125),
  (-5.79547119140625, 216.994140625),
  (-65.15277099609375, 279.4191589355469),
  (-8.99285888671875, 292.8171691894531),
  array([237, 172]),
  array([393, 557])],
 [(0.0, 0.0),
  (7.6929931640625, -6.554107666015625),
  (4.764373779296875, -5.847900390625),
  (38.415374755859375, -0.508941650390625),
  (31.204345703125, -1.48846435546875),
  (59.815887451171875, 45.49749755859375),
  (57.28936767578125, 42.453399658203125),
  (67.6025390625, 114.27499389648438),
  (61.52532958984375, 112.7723388671875),
  (44.89019775390625, 172.1085205078125),
  (41.22235107421875, 162.60720825195312),
  (51.287261962890625, 167.40484619140625),
  (49.38787841796875, 161.62930297851562),
  (58.562255859375, 237.55401611328125),
  (55.315887451171875, 223.601806640625),
  (76.28750610351562, 309.35247802734375),
  (60.177947998046875, 284.5975341796875),
  array([251, 179]),
  array([373, 552])],
 [(0.0, 0.0),
  (2.57562255859375, -4.3175048828125),
  (-6.34356689453125, -4.763275146484375),
  (3.147735595703125, -2.860870361328125),
  (-21.81280517578125, -4.084747314453125),
  (8.85382080078125, 18.059295654296875),
  (-42.307708740234375, 16.481536865234375),
  (18.7335205078125, 40.049835205078125),
  (-67.0233154296875, 39.51116943359375),
  (25.551116943359375, 64.59161376953125),
  (-70.8345947265625, 72.72067260742188),
  (-2.813507080078125, 70.55819702148438),
  (-36.429962158203125, 70.88388061523438),
  (-5.510711669921875, 103.88107299804688),
  (-44.34637451171875, 108.35491943359375),
  (-9.524505615234375, 138.07818603515625),
  (-53.66204833984375, 148.62368774414062),
  array([273, 284]),
  array([383, 476])],
 [(0.0, 0.0),
  (-6.473236083984375, -4.152862548828125),
  (-1.2772216796875, -4.89776611328125),
  (-29.955535888671875, -3.02880859375),
  (1.235137939453125, -2.7687530517578125),
  (-54.947784423828125, 14.851287841796875),
  (13.01654052734375, 17.695404052734375),
  (-68.34556579589844, 60.32958984375),
  (30.36151123046875, 66.15127563476562),
  (-55.43255615234375, 84.48593139648438),
  (32.791107177734375, 99.41363525390625),
  (-49.42779541015625, 93.24942016601562),
  (-3.79229736328125, 97.85037231445312),
  (-21.250518798828125, 136.92547607421875),
  (18.045989990234375, 143.39266967773438),
  (-20.041534423828125, 182.93478393554688),
  (0.873046875, 203.97427368164062),
  array([244, 209]),
  array([367, 465])],
 [(0.0, 0.0),
  (10.653839111328125, -5.625),
  (-4.137908935546875, -7.044219970703125),
  (34.519500732421875, -2.1103515625),
  (-5.0518798828125, -5.976470947265625),
  (52.690704345703125, 31.249481201171875),
  (-10.776214599609375, 25.418975830078125),
  (68.49337768554688, 74.12435913085938),
  (-34.45387268066406, 57.4661865234375),
  (56.938232421875, 110.03897094726562),
  (-44.25733947753906, 87.58969116210938),
  (33.754180908203125, 109.11611938476562),
  (-5.71728515625, 105.12692260742188),
  (43.472198486328125, 152.61563110351562),
  (-6.28851318359375, 143.41482543945312),
  (42.43585205078125, 187.73025512695312),
  (5.67529296875, 175.59518432617188),
  array([230, 276]),
  array([372, 535])],
 [(0.0, 0.0),
  (7.335479736328125, -8.407196044921875),
  (-11.83056640625, -8.5631103515625),
  (8.230133056640625, -6.15606689453125),
  (-36.927215576171875, -5.289825439453125),
  (17.535675048828125, 27.913604736328125),
  (-64.12939453125, 32.485748291015625),
  (27.374481201171875, 78.319091796875),
  (-90.19491577148438, 83.69873046875),
  (23.50933837890625, 121.98968505859375),
  (-91.99917602539062, 134.06512451171875),
  (-1.928436279296875, 131.73245239257812),
  (-54.48667907714844, 135.55426025390625),
  (-4.524658203125, 185.37387084960938),
  (-68.46302795410156, 196.96920776367188),
  (-17.9716796875, 223.47891235351562),
  (-64.18621826171875, 245.48635864257812),
  array([187, 295]),
  array([341, 626])],
 [(0.0, 0.0),
  (-6.3696441650390625, -1.2447509765625),
  (0.1607666015625, -3.669158935546875),
  (-16.67333984375, -21.33135986328125),
  (-10.2613525390625, -26.255615234375),
  (27.30767822265625, -26.958892822265625),
  (-22.0672607421875, -63.69000244140625),
  (64.6767578125, 46.2552490234375),
  (-59.22015380859375, -30.46746826171875),
  (26.41387939453125, 94.4302978515625),
  (-94.88986206054688, 22.20989990234375),
  (97.28533935546875, -81.29656982421875),
  (70.99200439453125, -94.07647705078125),
  (138.59039306640625, 3.01190185546875),
  (129.65707397460938, -37.599334716796875),
  (184.12451171875, -69.2459716796875),
  (186.49020385742188, -113.5908203125),
  array([ 92, 288]),
  array([457, 606])],
 [(0.0, 0.0),
  (0.712738037109375, -6.829559326171875),
  (-10.368377685546875, -4.91796875),
  (-9.48193359375, -2.275726318359375),
  (-36.828521728515625, 3.08026123046875),
  (0.943206787109375, 28.071044921875),
  (-54.525115966796875, 37.90252685546875),
  (15.496368408203125, 70.3748779296875),
  (-58.4737548828125, 80.48126220703125),
  (12.835235595703125, 104.3594970703125),
  (-43.603118896484375, 120.13931274414062),
  (1.809326171875, 106.09423828125),
  (-36.2353515625, 112.99600219726562),
  (4.72613525390625, 126.98825073242188),
  (-46.477630615234375, 142.37490844726562),
  (-11.574432373046875, 161.46368408203125),
  (-49.681610107421875, 185.66372680664062),
  array([231, 287]),
  array([343, 535])],
 [(0.0, 0.0),
  (-5.251190185546875, -1.785125732421875),
  (-2.2889862060546875, -5.29595947265625),
  (-10.972671508789062, -23.48779296875),
  (-15.780609130859375, -28.87847900390625),
  (33.705535888671875, -28.542449951171875),
  (-21.00848388671875, -64.4437255859375),
  (68.14996337890625, 46.141632080078125),
  (-52.29444885253906, -28.957275390625),
  (31.29412841796875, 94.1734619140625),
  (-92.84906005859375, 18.9263916015625),
  (110.28567504882812, -89.93588256835938),
  (79.94760131835938, -102.36199951171875),
  (149.486572265625, -3.44427490234375),
  (132.87918090820312, -42.097808837890625),
  (192.2579345703125, -83.57470703125),
  (196.46832275390625, -119.53375244140625),
  array([ 95, 287]),
  array([459, 602])],
 [(0.0, 0.0),
  (-10.304229736328125, -10.098678588867188),
  (7.94427490234375, -9.194717407226562),
  (-43.34002685546875, -4.83880615234375),
  (28.914794921875, -5.899444580078125),
  (-75.31533813476562, 52.672332763671875),
  (59.815216064453125, 53.34454345703125),
  (-108.71224975585938, 134.5653076171875),
  (89.17913818359375, 131.28228759765625),
  (-99.75228881835938, 204.52951049804688),
  (88.46255493164062, 204.23245239257812),
  (-56.580047607421875, 200.48715209960938),
  (38.8543701171875, 201.08758544921875),
  (-50.77680969238281, 308.0058288574219),
  (47.88232421875, 311.7034606933594),
  (-56.383392333984375, 419.6677551269531),
  (47.859100341796875, 415.5176086425781),
  array([158,  98]),
  array([429, 609])],
 [(0.0, 0.0),
  (4.7613525390625, -3.974639892578125),
  (6.165435791015625, -6.1558837890625),
  (24.10369873046875, 4.16845703125),
  (31.319122314453125, -2.436187744140625),
  (25.924224853515625, 40.35614013671875),
  (55.159149169921875, 32.3841552734375),
  (19.4783935546875, 91.955810546875),
  (60.75274658203125, 76.55303955078125),
  (2.80718994140625, 124.15615844726562),
  (36.81689453125, 108.44107055664062),
  (29.319091796875, 118.48126220703125),
  (46.200408935546875, 112.91860961914062),
  (28.58355712890625, 163.89633178710938),
  (40.7496337890625, 156.44921875),
  (39.46173095703125, 210.39163208007812),
  (30.700439453125, 201.47088623046875),
  array([297, 273]),
  array([392, 524])],
 [(0.0, 0.0),
  (-1.342254638671875, -4.538818359375),
  (1.2530517578125, -5.96221923828125),
  (-12.394439697265625, -10.272552490234375),
  (-6.0628662109375, -13.026519775390625),

In [92]:
columns = [
    'Nose', 
    'Left_Eye', 
    'Right_Eye', 
    'Left_Ear', 
    'Right_Ear', 
    'Left_Shoulder', 
    'Right_Shoulder', 
    'Left_Elbow', 
    'Right_Elbow', 
    'Left_Wrist', 
    'Right_Wrist', 
    'Left_Hip', 
    'Right_Hip', 
    'Left_Knee', 
    'Right_Knee', 
    'Left_Ankle', 
    'Right_Ankle',
    'BBoxes_p1',
    'BBoxes_p2'
]

In [93]:
df = pd.concat([
    pd.DataFrame(features, columns=columns),
    pd.DataFrame(targets, columns=['targets'])
], axis=1)
df.head()

,Nose,Left_Eye,Right_Eye,Left_Ear,Right_Ear,Left_Shoulder,Right_Shoulder,Left_Elbow,Right_Elbow,Left_Wrist,Right_Wrist,Left_Hip,Right_Hip,Left_Knee,Right_Knee,Left_Ankle,Right_Ankle,BBoxes_p1,BBoxes_p2,targets
0,"(0.0, 0.0)","(2.969818115234375, -3.343017578125)","(4.75787353515625, -4.371337890625)","(16.017974853515625, 0.763031005859375)","(24.252685546875, -3.33013916015625)","(22.419921875, 26.064361572265625)","(41.724853515625, 18.137359619140625)","(19.771759033203125, 60.0574951171875)","(51.76800537109375, 47.167877197265625)","(5.402587890625, 86.25283813476562)","(41.0611572265625, 67.84780883789062)","(21.951141357421875, 83.23684692382812)","(35.077728271484375, 76.83175659179688)","(16.240264892578125, 122.56332397460938)","(31.33636474609375, 111.39404296875)","(20.480865478515625, 165.65145874023438)","(37.42388916015625, 149.59182739257812)","[291, 289]","[366, 492]",not fall
1,"(0.0, 0.0)","(2.203216552734375, -5.118621826171875)","(-5.887847900390625, -6.091644287109375)","(-5.5640869140625, -3.91717529296875)","(-26.0697021484375, -5.3277587890625)","(-1.70098876953125, 21.91534423828125)","(-49.882415771484375, 22.85565185546875)","(5.635406494140625, 59.436004638671875)","(-70.62771606445312, 64.62896728515625)","(7.100677490234375, 90.60125732421875)","(-67.525634765625, 100.11004638671875)","(-15.848541259765625, 95.57498168945312)","(-46.81585693359375, 96.55389404296875)","(-20.456024169921875, 138.37966918945312)","(-58.841339111328125, 140.6790771484375)","(-32.686309814453125, 178.5489501953125)","(-61.57403564453125, 189.4188232421875)","[249, 312]","[347, 555]",not fall
2,"(0.0, 0.0)","(-0.56451416015625, -7.63092041015625)","(-8.668426513671875, -8.126861572265625)","(-25.22955322265625, -3.575927734375)","(-40.944427490234375, -3.416046142578125)","(-30.344024658203125, 41.03179931640625)","(-65.21206665039062, 44.718902587890625)","(-17.309722900390625, 111.17706298828125)","(-71.0257568359375, 115.06954956054688)","(-11.33380126953125, 169.08639526367188)","(-34.4765625, 172.41000366210938)","(-30.401611328125, 170.22705078125)","(-52.78472900390625, 174.1461181640625)","(-52.381683349609375, 242.91421508789062)","(-61.906036376953125, 248.68038940429688)","(-58.222900390625, 299.1534423828125)","(-67.9521484375, 316.8498229980469)","[232, 169]","[347, 561]",not fall
3,"(0.0, 0.0)","(12.612579345703125, -6.0320587158203125)","(-10.45867919921875, -7.76226806640625)","(25.917266845703125, 8.030670166015625)","(-28.996856689453125, 3.712005615234375)","(46.2015380859375, 54.033538818359375)","(-58.212921142578125, 49.78639221191406)","(71.405517578125, 107.01434326171875)","(-93.59994506835938, 99.63003540039062)","(72.35000610351562, 155.06396484375)","(-95.0213623046875, 157.5733642578125)","(21.578704833984375, 165.56607055664062)","(-45.820343017578125, 164.13714599609375)","(31.1717529296875, 230.83670043945312)","(-65.32342529296875, 231.77801513671875)","(30.572509765625, 285.08770751953125)","(-58.79730224609375, 291.7757263183594)","[195, 154]","[398, 518]",not fall
4,"(0.0, 0.0)","(4.9658203125, -3.471710205078125)","(5.11431884765625, -5.28509521484375)","(26.09405517578125, 2.82830810546875)","(23.7957763671875, -4.234710693359375)","(39.92218017578125, 34.65142822265625)","(38.3875732421875, 21.74945068359375)","(37.54119873046875, 75.71722412109375)","(29.748046875, 51.44708251953125)","(22.300140380859375, 106.97628784179688)","(12.896728515625, 76.3055419921875)","(29.7509765625, 101.79486083984375)","(29.24359130859375, 92.95401000976562)","(27.943695068359375, 141.6373291015625)","(26.30059814453125, 128.94952392578125)","(27.743408203125, 180.53558349609375)","(21.303436279296875, 164.8646240234375)","[294, 258]","[382, 486]",not fall

In [94]:
df.tail()

,Nose,Left_Eye,Right_Eye,Left_Ear,Right_Ear,Left_Shoulder,Right_Shoulder,Left_Elbow,Right_Elbow,Left_Wrist,Right_Wrist,Left_Hip,Right_Hip,Left_Knee,Right_Knee,Left_Ankle,Right_Ankle,BBoxes_p1,BBoxes_p2,targets
228,"(0.0, 0.0)","(-5.749755859375, -1.284637451171875)","(13.784759521484375, 3.816986083984375)","(-8.40185546875, 3.57757568359375)","(35.50726318359375, 12.13275146484375)","(-27.34088134765625, 22.230224609375)","(56.21514892578125, 28.79730224609375)","(-87.76412963867188, -9.3553466796875)","(59.86541748046875, -2.035919189453125)","(-147.61801147460938, -83.32843017578125)","(-36.50079345703125, -63.258026123046875)","(-24.02630615234375, -44.46331787109375)","(21.192657470703125, -39.4130859375)","(-51.05255126953125, -178.1220703125)","(-36.445648193359375, -157.38949584960938)","(-51.650970458984375, -278.28338623046875)","(-63.624664306640625, -266.5418701171875)","[163, 154]","[487, 592]",fall
229,"(0.0, 0.0)","(5.192352294921875, -2.391265869140625)","(15.23968505859375, -0.267822265625)","(49.82049560546875, 4.708526611328125)","(62.540283203125, 8.045501708984375)","(71.17962646484375, -0.784393310546875)","(98.46978759765625, 28.548492431640625)","(-38.24949645996094, -35.76898193359375)","(63.20208740234375, 42.0836181640625)","(-182.66366577148438, -96.23089599609375)","(-109.55949401855469, 23.068695068359375)","(67.86962890625, -31.7064208984375)","(75.2239990234375, -29.018310546875)","(-35.944366455078125, -63.142974853515625)","(-49.65907287597656, -33.652435302734375)","(-147.2527618408203, -135.72232055664062)","(-161.43301391601562, -112.66824340820312)","[22, 280]","[467, 540]",fall
230,"(0.0, 0.0)","(1.5728759765625, 0.986053466796875)","(6.92340087890625, -19.03179931640625)","(8.415863037109375, 5.2123870849609375)","(25.310577392578125, -38.49176025390625)","(53.449310302734375, 63.515472412109375)","(64.34170532226562, -43.345001220703125)","(77.80947875976562, 119.38540649414062)","(54.73321533203125, -53.38720703125)","(31.05419921875, 75.2777099609375)","(4.881378173828125, 8.3724365234375)","(184.97296142578125, 71.33126831054688)","(197.62893676757812, 21.5780029296875)","(164.04986572265625, 1.8660125732421875)","(192.84521484375, -100.01736450195312)","(235.43560791015625, 42.228271484375)","(256.8013916015625, -43.72996520996094)","[195, 128]","[569, 378]",fall
231,"(0.0, 0.0)","(-6.1801605224609375, -4.9896240234375)","(-4.0653533935546875, -4.75469970703125)","(-9.917449951171875, -9.6912841796875)","(-2.5818023681640625, -5.7222900390625)","(28.845123291015625, -1.377593994140625)","(38.52912902832031, -22.070281982421875)","(59.89129638671875, -43.67974853515625)","(71.59310913085938, -87.43264770507812)","(49.77642822265625, -69.6981201171875)","(63.944793701171875, -86.42950439453125)","(168.92625427246094, -36.3680419921875)","(173.6680145263672, -43.174102783203125)","(219.5813751220703, -124.91424560546875)","(220.5472869873047, -170.71737670898438)","(289.5345458984375, -77.79312133789062)","(282.605712890625, -106.67826843261719)","[13, 191]","[443, 468]",fall
232,"(0.0, 0.0)","(-3.929351806640625, 1.806671142578125)","(5.281982421875, -13.4349365234375)","(-29.427093505859375, 26.517974853515625)","(9.601776123046875, -6.44927978515625)","(-10.222503662109375, 93.81375122070312)","(54.72747802734375, 30.580322265625)","(16.930450439453125, 181.2559814453125)","(97.77902221679688, 91.35287475585938)","(10.78106689453125, 178.57479858398438)","(79.3013916015625, 148.79910278320312)","(114.61990356445312, 161.34893798828125)","(165.3359375, 133.55648803710938)","(130.73550415039062, 99.47372436523438)","(198.9720458984375, 38.541229248046875)","(196.53912353515625, 132.70016479492188)","(252.43402099609375, 82.23806762695312)","[110, 227]","[464, 505]",fall

In [95]:
## Save the data
df.to_csv('fall_not_fall_with_coordinate.csv', index=False)

### Visualize the dataset

In [14]:
import seaborn as sns
# sns.pairplot(df, hue='targets')